# Use a specific Node.js base image
FROM node:22.3-alpine3.19

# Create a directory for the Jenkins test
RUN mkdir /home/jenkinstest

# Add a new user and group (e.g., tempuser)
RUN addgroup -S tempuser && adduser -S tempuser -G tempuser

# Set the working directory
WORKDIR /home/jenkinstest

# Copy all files from the current directory to the working directory
COPY . .

# Change ownership of the directory to the new user
RUN chown -R tempuser:tempuser /home/jenkinstest

# Switch to the new user
USER tempuser

# Optional: Add a build trigger instruction
ONBUILD RUN echo "Jenkins Test - Container build successful"

# Specify the command to run
CMD ["node", "index.js"]
